### ISSUE TITLE
There are some bugs in loop

### ISSUE THREAD

**Issue by Asphelzhn** [ihtisham1211/Attentiveness-Monitoring-System#1]
When I ran this code, it occured "Traceback (most recent call last):
  File "Run_AMS.py", line 106, in <module>
    for (x, y) in temp:
NameError: name 'temp' is not defined"
I think there are some bugs between those loops. Could you help me fix them. Thanks.

`temp = '' # temp for shape
    #HEAD START
    # loop over the face detections
    for (i, rect) in enumerate(faces):
        shape = predictor(gray_image, rect) #Facial landmarks of the ROI and convert the 68 points into a NumPy array
        shape = face_utils.shape_to_np(shape)
        temp = shape
        #Eye start
        # extract the left and right eye coordinates, then use the
        # coordinates to compute the eye aspect ratio for both eyes
        leftEye = shape[lStart:lEnd]
        rightEye = shape[rStart:rEnd]
        leftEAR = eye_aspect_ratio(leftEye)# applying EAR
        rightEAR = eye_aspect_ratio(rightEye)# applying EAR

        # average the eye aspect ratio together for both eyes
        ear = (leftEAR + rightEAR) / 2.0

        # loop over the (x, y)-coordinates for the facial landmarks
    # and draw them on the image
    for (x, y) in temp:
        a = a + 1
        if a== 9 or a == 31 or a == 37 or a == 46 or a == 49 or a == 55: #chin  - Nose - left Eye - Right Eye  - Left mouth - right Mouth
            cv2.circle(rgb_image, (x, y), 1, (0, 0, 255), -1)
            landmarks.append(x)
            landmarks.append(y)

    imgpts, modelpts, rotate_degree, nose = face_orientation(rgb_image, landmarks) #head pose function.

#----------------------------------------------------------------------------------------------
#---------------------------->Labeling of Attentive and Unattentive<---------------------------
#----------------------------------------------------------------------------------------------

    #Emotion labeling
    if emotion_text == 'angry' or emotion_text == 'fear' or emotion_text == 'sad':
        emotion_mode = 'Not Attentive'
    elif emotion_text == 'happy' or emotion_text == 'surprise' or emotion_text == 'neutral':
        emotion_mode = 'Attentive'
`

**Comment by ihtisham1211** [comment]
Kindly tell me which compiler are you using? I ran it on spyder and there were no issues that I faced like this. 👍

**Comment by Asphelzhn** [comment]
> Kindly tell me which compiler are you using? I ran it on spyder and there were no issues that I faced like this. 👍

Thank you. I have solved the problem. It caused by the misuse of space and "\t". I wonder if there is a paper to describe your opinion, and I want to read it. Thanks

**Comment by ihtisham1211** [comment]
It was my FYP and I would like to write a paper about it but I don't have any free time, in the future maybe ill write one xD
